-- MySQL Script generated by MySQL Workbench
-- Fri Dec 24 05:17:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb DATABASE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `furniture` DEFAULT CHARACTER SET utf8 ;
USE `furniture` ;




CREATE DATABASE IF NOT EXISTS `furniture_store` DEFAULT CHARACTER SET utf8;
USE `furniture_store`;




-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posts` (
  `idposts` INT NOT NULL AUTO_INCREMENT,
  `post_name` VARCHAR(50) NOT NULL,
  `salary` DECIMAL(10,2) NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idposts`, `users_idusers`),
  INDEX `fk_posts_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `idemployees` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `passport` VARCHAR(11) NOT NULL,
  `inn` VARCHAR(12) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `date` INT(11) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `posts_idposts` INT NOT NULL,
  PRIMARY KEY (`idemployees`, `posts_idposts`),
  INDEX `fk_employees_posts1_idx` (`posts_idposts` ASC) VISIBLE,
  -- UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  -- UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  -- UNIQUE INDEX `inn_UNIQUE` (`inn` ASC) VISIBLE,
  -- UNIQUE INDEX `passport_UNIQUE` (`passport` ASC) VISIBLE,
  CONSTRAINT `fk_employees_posts1`
    FOREIGN KEY (`posts_idposts`)
    REFERENCES `mydb`.`posts` (`idposts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`monetary_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`monetary_transactions` (
  `idmonetary_transactions` INT NOT NULL AUTO_INCREMENT,
  `appointment` SET('purchase', 'order') NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`idmonetary_transactions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchases` (
  `idpurchases` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `monetary_transactions_idmonetary_transactions` INT NOT NULL,
  PRIMARY KEY (`idpurchases`, `monetary_transactions_idmonetary_transactions`),
  INDEX `fk_purchases_monetary_transactions1_idx` (`monetary_transactions_idmonetary_transactions` ASC) VISIBLE,
  CONSTRAINT `fk_purchases_monetary_transactions1`
    FOREIGN KEY (`monetary_transactions_idmonetary_transactions`)
    REFERENCES `mydb`.`monetary_transactions` (`idmonetary_transactions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `idproducts` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(50) NOT NULL,
  `quantity` INT(10) NOT NULL,
  `purchase_price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `selling_price` DECIMAL(10,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`idproducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchase_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase_products` (
  `idpurchase_products` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT(10) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `purchases_idpurchases` INT NOT NULL,
  `products_idproducts` INT NOT NULL,
  PRIMARY KEY (`idpurchase_products`, `purchases_idpurchases`, `products_idproducts`),
  INDEX `fk_purchase_products_purchases1_idx` (`purchases_idpurchases` ASC) VISIBLE,
  INDEX `fk_purchase_products_products1_idx` (`products_idproducts` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_products_purchases1`
    FOREIGN KEY (`purchases_idpurchases`)
    REFERENCES `mydb`.`purchases` (`idpurchases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_products_products1`
    FOREIGN KEY (`products_idproducts`)
    REFERENCES `mydb`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`buyers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`buyers` (
  `idbuyers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idbuyers`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `idorders` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `employees_idemployees` INT NOT NULL,
  `employees_posts_idposts` INT NOT NULL,
  `monetary_transactions_idmonetary_transactions` INT NOT NULL,
  `buyers_idbuyers` INT NOT NULL,
  PRIMARY KEY (`idorders`, `employees_idemployees`, `employees_posts_idposts`, `monetary_transactions_idmonetary_transactions`, `buyers_idbuyers`),
  INDEX `fk_orders_employees1_idx` (`employees_idemployees` ASC, `employees_posts_idposts` ASC) VISIBLE,
  INDEX `fk_orders_monetary_transactions1_idx` (`monetary_transactions_idmonetary_transactions` ASC) VISIBLE,
  INDEX `fk_orders_buyers1_idx` (`buyers_idbuyers` ASC) VISIBLE,
  CONSTRAINT `fk_orders_employees1`
    FOREIGN KEY (`employees_idemployees` , `employees_posts_idposts`)
    REFERENCES `mydb`.`employees` (`idemployees` , `posts_idposts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_monetary_transactions1`
    FOREIGN KEY (`monetary_transactions_idmonetary_transactions`)
    REFERENCES `mydb`.`monetary_transactions` (`idmonetary_transactions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_buyers1`
    FOREIGN KEY (`buyers_idbuyers`)
    REFERENCES `mydb`.`buyers` (`idbuyers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_products` (
  `idorder_products` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT(10) NOT NULL,
  `amount` DECIMAL(10,2) UNSIGNED NOT NULL,
  `orders_idorders` INT NOT NULL,
  `orders_employees_idemployees` INT NOT NULL,
  `orders_employees_posts_idposts` INT NOT NULL,
  `products_idproducts` INT NOT NULL,
  PRIMARY KEY (`idorder_products`, `orders_idorders`, `orders_employees_idemployees`, `orders_employees_posts_idposts`, `products_idproducts`),
  INDEX `fk_order_products_orders1_idx` (`orders_idorders` ASC, `orders_employees_idemployees` ASC, `orders_employees_posts_idposts` ASC) VISIBLE,
  INDEX `fk_order_products_products1_idx` (`products_idproducts` ASC) VISIBLE,
  CONSTRAINT `fk_order_products_orders1`
    FOREIGN KEY (`orders_idorders` , `orders_employees_idemployees` , `orders_employees_posts_idposts`)
    REFERENCES `mydb`.`orders` (`idorders` , `employees_idemployees` , `employees_posts_idposts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_products_products1`
    FOREIGN KEY (`products_idproducts`)
    REFERENCES `mydb`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
